In [1]:
import requests
from config import key
from pprint import pprint
import time
import pandas as pd
key

'RGAPI-740c7d6c-1b88-4575-86f8-cea3a2a8e1c7'

In [68]:
tier = ["GRANDMASTER", "CHALLENGER"]
division = ["I", "II", "III", "IV"]
page = 1
combined_data = pd.DataFrame()
emptypage = False

while emptypage == False:
    url = f"https://na1.api.riotgames.com/lol/league-exp/v4/entries/RANKED_SOLO_5x5/"\
          f"PLATINUM/I?page={page}&api_key={key}"
    data = requests.get(url).json()
    if data == []:
        print(f"You've reached empty page, the last page is {page -1}")
        emptypage = True
    if type(data) is dict:
        print(data["status"]["message"])
        break
    data_df = pd.DataFrame(data)
    combined_data = combined_data.append(data_df, ignore_index=True)
    page += 1
    if page % 10 == 0:
        print ("10 pages done, now sleeping for 15 seconds to aovid reaching limit")
        time.sleep(15)

combined_data

10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
10 pages done, now sleeping for 15 seconds to aovid reaching limit
You've reached empty page, the last page is 132

,leagueId,queueType,tier,rank,summonerId,summonerName,leaguePoints,wins,losses,veteran,inactive,freshBlood,hotStreak,miniSeries
0,e9535aff-8d6f-4d83-aa68-be700453edf8,RANKED_SOLO_5x5,PLATINUM,I,5F-LihRZcmqBuomj-QOG18dHgx0xEP8YfWVsC7C6ItRPD5n5,xTc4,75,99,95,False,False,False,False,NaN
1,2a6ec9b0-cc92-48cc-baa8-c80994d14bba,RANKED_SOLO_5x5,PLATINUM,I,s3TBWBamGgVPT0N1Vqx4SI3q4wMXdfnoBt4RE4jEB5uHpxmF,play to think,75,109,84,False,False,False,False,NaN
2,ced18464-d729-4402-8f39-7f7e43c53865,RANKED_SOLO_5x5,PLATINUM,I,NsTbVflZ9Be1UEwxTTxA-rvr_ccyz9j15lcGXfFeOvxYDfS1,Violence Li,75,148,112,False,False,False,False,NaN
3,5bc80f3d-d247-4beb-a9ca-27acb9847e1b,RANKED_SOLO_5x5,PLATINUM,I,_m5OgDeQSIJvZgT8S60-KUAzxeOqDr52d9bMpYuPk2SIdYT1,JudgeJudySmurfin,0,12,10,False,False,False,False,NaN
4,5760a640-7af9-4935-bbb8-6f3ed3ecd6bf,RANKED_SOLO_5x5,PLATINUM,I,zgoqhmfd02HpDGGgEp5z9Lvpjz8VA7xxbAAvMyWCVKws5OkO,Dàncer,36,7,10,False,False,False,False,NaN

In [69]:
combined_data

,leagueId,queueType,tier,rank,summonerId,summonerName,leaguePoints,wins,losses,veteran,inactive,freshBlood,hotStreak,miniSeries
0,e9535aff-8d6f-4d83-aa68-be700453edf8,RANKED_SOLO_5x5,PLATINUM,I,5F-LihRZcmqBuomj-QOG18dHgx0xEP8YfWVsC7C6ItRPD5n5,xTc4,75,99,95,False,False,False,False,NaN
1,2a6ec9b0-cc92-48cc-baa8-c80994d14bba,RANKED_SOLO_5x5,PLATINUM,I,s3TBWBamGgVPT0N1Vqx4SI3q4wMXdfnoBt4RE4jEB5uHpxmF,play to think,75,109,84,False,False,False,False,NaN
2,ced18464-d729-4402-8f39-7f7e43c53865,RANKED_SOLO_5x5,PLATINUM,I,NsTbVflZ9Be1UEwxTTxA-rvr_ccyz9j15lcGXfFeOvxYDfS1,Violence Li,75,148,112,False,False,False,False,NaN
3,5bc80f3d-d247-4beb-a9ca-27acb9847e1b,RANKED_SOLO_5x5,PLATINUM,I,_m5OgDeQSIJvZgT8S60-KUAzxeOqDr52d9bMpYuPk2SIdYT1,JudgeJudySmurfin,0,12,10,False,False,False,False,NaN
4,5760a640-7af9-4935-bbb8-6f3ed3ecd6bf,RANKED_SOLO_5x5,PLATINUM,I,zgoqhmfd02HpDGGgEp5z9Lvpjz8VA7xxbAAvMyWCVKws5OkO,Dàncer,36,7,10,False,False,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26871,8b24a2c5-a959-47ae-9075-aaab585053f5,RANKED_SOLO_5x5,PLATINUM,I,mlyj5qQMSXux9S-m2RmrukxZskFN3A0r8UARk7sZTMhvPxI,SyrianRefugee V2,47,93,112,False,False,False,False,NaN
26872,a371a537-3ea8-4b80-b76b-1542e81b8cab,RANKED_SOLO_5x5,PLATINUM,I,b1-9QZ-t23dEIySgWtz_YqmD7GHTOuZrakqWF4xIrRYAfk8,Coffeene,20,25,24,False,False,False,False,NaN
26873,88e3835f-6a87-49b3-8dad-b2ad52256426,RANKED_SOLO_5x5,PLATINUM,I,OBtoQRoK49zAREV5hZiBXdlaRkFrYFrSkAXS41izF9blcgE,Trágedy,65,150,134,False,False,False,False,NaN
26874,a03e3b84-7e63-4d97-a7b8-f4a837542571,RANKED_SOLO_5x5,PLATINUM,I,DWa_aWsz7LLJ8kxNTiKUfPBmBP5cRyz3KHPjlZ2PmwMyKT0,vampirical,75,133,143,False,False,False,False,NaN
26875,d2bd4cbf-5b5a-4514-b8e4-f7947328b6cf,RANKED_SOLO_5x5,PLATINUM,I,AHwnvwh9Nexa90qPSXyZ03FadM8CuZsWDKERqmhz3IZ21tM,Low,75,53,53,False,False,False,False,NaN